[versions]
biometric-ktx = "1.2.0-alpha05"
core-ktx = "1.10.1"
activity-compose = "1.7.2"
material3 = "1.2.0-alpha02"
appcompat = "1.6.1"
annotation = "1.6.0"
librepass-client = "0.1.0-SNAPSHOT-02"
accompanist = "0.31.3-beta"
material-icons-extended = "1.5.0-beta02"
kotlinx-coroutines-android = "1.7.1"
navigation-compose = "2.6.0"
compose-bom = "2023.06.00"
room = "2.5.1"
compose-compiler = "1.4.7"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

# plugins
com-android-application = "8.1.0-beta05"
org-jetbrains-kotlin-android = "1.8.21"
google-ksp = "1.8.21-1.0.11"
gradle-ktlint = "11.3.2"

[libraries]
# androidx
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric-ktx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# librepass client
librepass-client = { module = "dev.medzik.librepass:client", version.ref = "librepass-client" }

# com.google.accompanist
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# kotlin
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# debug
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

# compose compiler
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
com-android-library = { id = "com.android.library", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }

[bundles]
